apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.runtimeConfig.name }}
  labels:
    {{- include "rag-ingestion.labels" . | nindent 4 }}
data:
  RAG_CONFIG_PROFILE: "container"
  RAG_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.runtimeConfig.kafkaBootstrapServers | quote }}
  RAG_MINIO_ENDPOINT: {{ .Values.runtimeConfig.minioEndpoint | quote }}
  RAG_MINIO_SECURE: {{ .Values.runtimeConfig.minioSecure | quote }}
  RAG_MINIO_SOURCE_BUCKET: {{ .Values.runtimeConfig.minioSourceBucket | quote }}
  RAG_MINIO_ARTIFACT_BUCKET: {{ .Values.runtimeConfig.minioArtifactBucket | quote }}
  RAG_QDRANT_URL: {{ .Values.runtimeConfig.qdrantUrl | quote }}
  RAG_QDRANT_COLLECTION: {{ .Values.runtimeConfig.qdrantCollection | quote }}
  RAG_BGE_MODEL_NAME: {{ .Values.runtimeConfig.bgeModelName | quote }}
  RAG_OTEL_SERVICE_NAME: {{ .Values.runtimeConfig.otelServiceName | quote }}
  RAG_OBSERVABILITY_MODE: {{ .Values.runtimeConfig.observabilityMode | quote }}
  RAG_TRACING_ENABLED: {{ .Values.runtimeConfig.tracingEnabled | quote }}
  RAG_OTEL_METRICS_EXPORT_INTERVAL_SECONDS: {{ .Values.runtimeConfig.otelMetricsExportIntervalSeconds | quote }}
  RAG_OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.runtimeConfig.otelExporterOtlpEndpoint | quote }}
