[CmdletBinding()]
param(
    [string]$SecretsPath = "secrets/local-access.env",
    [switch]$Rotate,
    [switch]$PrepareOnly
)

$ErrorActionPreference = "Stop"

function New-RandomSecret {
    param([int]$ByteCount = 32)

    $bytes = [byte[]]::new($ByteCount)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
}

function Read-EnvFile {
    param([string]$Path)

    $values = @{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $values
    }

    foreach ($line in Get-Content -LiteralPath $Path) {
        if ($line -match '^\s*#' -or [string]::IsNullOrWhiteSpace($line)) { continue }
        $pair = $line -split '=', 2
        if ($pair.Count -eq 2) { $values[$pair[0]] = $pair[1] }
    }
    return $values
}

function Write-EnvFile {
    param([string]$Path, [hashtable]$Values)

    $directory = Split-Path -Parent $Path
    if ($directory) { New-Item -ItemType Directory -Force -Path $directory | Out-Null }
    $orderedKeys = $Values.Keys | Sort-Object
    @(
        "# Generated by scripts/provision_local_access.ps1. Do not commit.",
        "# Rotate with: .\scripts\provision_local_access.ps1 -Rotate"
    ) + ($orderedKeys | ForEach-Object { "$_=$($Values[$_])" }) |
        Set-Content -LiteralPath $Path -Encoding ascii
}

function ConvertTo-SqlLiteral {
    param([string]$Value)
    return "'" + $Value.Replace("'", "''") + "'"
}

$platformSecretNames = @(
    "POSTGRES_PASSWORD",
    "MINIO_ROOT_PASSWORD",
    "GRAFANA_ADMIN_PASSWORD"
)

$secretNames = @(
    "POSTGRES_MIGRATOR_PASSWORD",
    "POSTGRES_DOCUMENT_FETCHER_PASSWORD",
    "POSTGRES_CONTENT_EXTRACTOR_PASSWORD",
    "POSTGRES_CHUNKER_PASSWORD",
    "POSTGRES_EMBEDDER_PASSWORD",
    "POSTGRES_INDEXER_PASSWORD",
    "POSTGRES_OUTBOX_PUBLISHER_PASSWORD",
    "POSTGRES_QUERY_API_PASSWORD",
    "QDRANT_ADMIN_API_KEY",
    "QDRANT_READ_ONLY_API_KEY"
)

$secrets = Read-EnvFile -Path $SecretsPath
if (-not $secrets.ContainsKey("MINIO_ROOT_USER") -or [string]::IsNullOrWhiteSpace($secrets["MINIO_ROOT_USER"])) {
    $secrets["MINIO_ROOT_USER"] = "minio-root"
}
foreach ($name in $platformSecretNames) {
    if (-not $secrets.ContainsKey($name) -or [string]::IsNullOrWhiteSpace($secrets[$name])) {
        $secrets[$name] = New-RandomSecret
    }
}
foreach ($name in $secretNames) {
    if ($Rotate -or -not $secrets.ContainsKey($name) -or [string]::IsNullOrWhiteSpace($secrets[$name])) {
        $secrets[$name] = New-RandomSecret
    }
}
Write-EnvFile -Path $SecretsPath -Values $secrets

$workerEnvironments = @(
    @{ Name = "migration"; Login = "rag_migration_login"; Password = $secrets["POSTGRES_MIGRATOR_PASSWORD"]; QdrantKey = $secrets["QDRANT_ADMIN_API_KEY"] },
    @{ Name = "document-fetcher"; Login = "rag_document_fetcher"; Password = $secrets["POSTGRES_DOCUMENT_FETCHER_PASSWORD"]; QdrantKey = $secrets["QDRANT_READ_ONLY_API_KEY"] },
    @{ Name = "content-extractor"; Login = "rag_content_extractor"; Password = $secrets["POSTGRES_CONTENT_EXTRACTOR_PASSWORD"]; QdrantKey = $secrets["QDRANT_READ_ONLY_API_KEY"] },
    @{ Name = "chunker"; Login = "rag_chunker"; Password = $secrets["POSTGRES_CHUNKER_PASSWORD"]; QdrantKey = $secrets["QDRANT_READ_ONLY_API_KEY"] },
    @{ Name = "embedder"; Login = "rag_embedder"; Password = $secrets["POSTGRES_EMBEDDER_PASSWORD"]; QdrantKey = $secrets["QDRANT_READ_ONLY_API_KEY"] },
    @{ Name = "indexer"; Login = "rag_indexer"; Password = $secrets["POSTGRES_INDEXER_PASSWORD"]; QdrantKey = $secrets["QDRANT_ADMIN_API_KEY"] },
    @{ Name = "outbox-publisher"; Login = "rag_outbox_publisher"; Password = $secrets["POSTGRES_OUTBOX_PUBLISHER_PASSWORD"]; QdrantKey = $secrets["QDRANT_READ_ONLY_API_KEY"] },
    @{ Name = "query-api"; Login = "rag_query_api"; Password = $secrets["POSTGRES_QUERY_API_PASSWORD"]; QdrantKey = $secrets["QDRANT_READ_ONLY_API_KEY"] }
)

foreach ($worker in $workerEnvironments) {
    $workerPath = "secrets/workers/$($worker.Name).env"
    Write-EnvFile -Path $workerPath -Values @{
        RAG_POSTGRES_DSN = "postgresql+asyncpg://$($worker.Login):$($worker.Password)@postgres:5432/rag_ingestion"
        RAG_QDRANT_API_KEY = $worker.QdrantKey
        RAG_QDRANT_READ_ONLY_API_KEY = $secrets["QDRANT_READ_ONLY_API_KEY"]
    }
}

if ($PrepareOnly) {
    Write-Host "Prepared local platform, worker, and Qdrant credentials in $SecretsPath."
    Write-Host "Start Compose, then run this script again without -PrepareOnly to create PostgreSQL roles."
    return
}

$psqlArgs = @(
    "compose", "-f", "deploy/docker/docker-compose.yml",
    "--env-file", "config/env/container.env", "--env-file", $SecretsPath,
    "exec", "-T", "postgres", "psql", "-U", "rag", "-d", "rag_ingestion"
)

foreach ($migrationPath in @(
    "migrations/001_enterprise_rag_metadata.sql",
    "migrations/002_database_roles_and_privileges.sql"
)) {
    Get-Content -Raw -LiteralPath $migrationPath | & docker @psqlArgs
    if ($LASTEXITCODE -ne 0) { throw "Failed to apply $migrationPath." }
}

$roles = @(
    @{ Login = "rag_migration_login"; Group = "rag_ingestion_migrator"; Password = $secrets["POSTGRES_MIGRATOR_PASSWORD"]; Limit = 2 },
    @{ Login = "rag_document_fetcher"; Group = "rag_ingestion_runtime"; Password = $secrets["POSTGRES_DOCUMENT_FETCHER_PASSWORD"]; Limit = 4 },
    @{ Login = "rag_content_extractor"; Group = "rag_ingestion_runtime"; Password = $secrets["POSTGRES_CONTENT_EXTRACTOR_PASSWORD"]; Limit = 4 },
    @{ Login = "rag_chunker"; Group = "rag_ingestion_runtime"; Password = $secrets["POSTGRES_CHUNKER_PASSWORD"]; Limit = 4 },
    @{ Login = "rag_embedder"; Group = "rag_ingestion_runtime"; Password = $secrets["POSTGRES_EMBEDDER_PASSWORD"]; Limit = 4 },
    @{ Login = "rag_indexer"; Group = "rag_ingestion_runtime"; Password = $secrets["POSTGRES_INDEXER_PASSWORD"]; Limit = 4 },
    @{ Login = "rag_outbox_publisher"; Group = "rag_ingestion_outbox_publisher"; Password = $secrets["POSTGRES_OUTBOX_PUBLISHER_PASSWORD"]; Limit = 2 },
    @{ Login = "rag_query_api"; Group = "rag_ingestion_query_reader"; Password = $secrets["POSTGRES_QUERY_API_PASSWORD"]; Limit = 8 }
)

$sql = @("\\set ON_ERROR_STOP on")
foreach ($role in $roles) {
    $login = $role.Login
    $password = ConvertTo-SqlLiteral $role.Password
    $sql += @"
DO `$`$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$login') THEN
        CREATE ROLE $login LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION CONNECTION LIMIT $($role.Limit) PASSWORD $password;
    ELSE
        ALTER ROLE $login LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION CONNECTION LIMIT $($role.Limit) PASSWORD $password;
    END IF;
END `$`$;
GRANT $($role.Group) TO $login;
"@
}

($sql -join "`n") | & docker @psqlArgs
if ($LASTEXITCODE -ne 0) { throw "PostgreSQL role provisioning failed." }

Write-Host "Created or rotated 8 PostgreSQL login users."
Write-Host "Generated Qdrant admin/read-only keys in $SecretsPath."
Write-Host "Created per-worker container settings in secrets/workers/."
Write-Host "Restart the Compose stack with both --env-file arguments to apply Qdrant keys."
